# Generated by Django 5.2.3 on 2025-07-03 11:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_code', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Shop code must be uppercase alphanumeric with no spaces', regex='^[A-Z0-9]+$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#ffffff', max_length=7)),
                ('percentage', models.FloatField(help_text='Probability percentage (e.g., 25.0)')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spinwheelapp.shopprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_bill_number', models.BooleanField(default=False, help_text='Enable to require bill number for spin entries')),
                ('require_social_verification', models.BooleanField(default=False, help_text='Enable to require social media verification before spinning')),
                ('require_screenshot', models.BooleanField(default=False, help_text='Enable to require screenshot proof for social verification')),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('google_review_url', models.URLField(blank=True, null=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spinwheelapp.shopprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SpinEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bill_number', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid  phone number', regex='^[6-9]\\d{9}$')])),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spinwheelapp.offer')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spinwheelapp.shopprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SocialVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_screenshot', models.ImageField(help_text='Upload screenshot of Instagram follow', upload_to='verifications/instagram/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('google_review_screenshot', models.ImageField(help_text='Upload screenshot of Google review', upload_to='verifications/google/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_verification', to='spinwheelapp.spinentry')),
            ],
        ),
        migrations.AddConstraint(
            model_name='spinentry',
            constraint=models.UniqueConstraint(condition=models.Q(('bill_number__isnull', False)), fields=('shop', 'bill_number'), name='unique_bill_per_shop'),
        ),
    ]
