# Generated by Django 5.2.3 on 2025-07-30 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinwheelapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsettings',
            name='require_screenshot',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='require_social_verification',
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='enable_google_review',
            field=models.BooleanField(default=False, help_text='Enable Google review verification'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='enable_instagram_verification',
            field=models.BooleanField(default=False, help_text='Enable Instagram follow verification'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='require_google_screenshot',
            field=models.BooleanField(default=False, help_text='Require screenshot proof for Google review verification'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='require_instagram_screenshot',
            field=models.BooleanField(default=False, help_text='Require screenshot proof for Instagram verification'),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='google_review_url',
            field=models.URLField(blank=True, help_text='Your Google review URL (required if Google review verification is enabled)', null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='shopsettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Your Instagram profile URL (required if Instagram verification is enabled)', null=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])]),
        ),
        migrations.AlterField(
            model_name='socialverification',
            name='google_review_screenshot',
            field=models.ImageField(blank=True, help_text='Upload screenshot of Google review', null=True, upload_to='verifications/google/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='socialverification',
            name='instagram_screenshot',
            field=models.ImageField(blank=True, help_text='Upload screenshot of Instagram follow', null=True, upload_to='verifications/instagram/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
