# Generated by Django 5.2.3 on 2025-06-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinwheelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='probability',
            field=models.PositiveIntegerField(default=1, help_text='Chance weight (higher = more likely to be picked)'),
        ),
    ]
