# Generated by Django 5.2.3 on 2025-06-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinwheelapp', '0002_offer_probability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='probability',
        ),
        migrations.AddField(
            model_name='offer',
            name='percentage',
            field=models.FloatField(default=25, help_text='Probability percentage (e.g., 25.0)'),
            preserve_default=False,
        ),
    ]
