# Generated by Django 5.2.3 on 2025-08-30 10:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinwheelapp', '0002_remove_shopsettings_require_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for the offer (max 50 characters)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='whatsapp_number',
            field=models.CharField(default='8848647616', help_text='WhatsApp number with country code (e.g. 919876543210)', max_length=12, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Enter a valid phone number')]),
        ),
    ]
