# Generated by Django 5.2.3 on 2025-07-04 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spinwheelapp', '0003_spinentry_unique_bill_per_shop'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='spinentry',
            name='unique_bill_per_shop',
        ),
    ]
