# Generated by Django 5.2.3 on 2025-06-26 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinwheelapp', '0003_remove_offer_probability_offer_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spins_per_day', models.IntegerField(choices=[(1, '1 spin per day'), (2, '2 spins per day'), (0, 'Unlimited spins')], default=1, help_text='Maximum spins allowed per mobile number per day')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spinwheelapp.shopprofile')),
            ],
        ),
    ]
