# Generated by Django 5.2.3 on 2025-06-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinwheelapp', '0004_shopsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='require_bill_number',
            field=models.BooleanField(default=False, help_text='Enable to require bill number for spin entries'),
        ),
        migrations.AddField(
            model_name='spinentry',
            name='bill_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
