# Generated by Django 5.2.3 on 2025-07-04 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinwheelapp', '0004_remove_spinentry_unique_bill_per_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='whatsapp_number',
            field=models.CharField(default=919988776655, help_text='Include country code (e.g., 919876543210)', max_length=15, validators=[django.core.validators.RegexValidator('^[6-9]\\d{9}$', 'Enter valid WhatsApp number')]),
        ),
    ]
