# Generated by Django 5.2.3 on 2025-07-01 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinwheelapp', '0005_shopsettings_require_bill_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinentry',
            name='country_code',
            field=models.CharField(default='+91', max_length=5),
        ),
        migrations.AlterField(
            model_name='spinentry',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian phone number', regex='^[6-9]\\d{9}$')]),
        ),
    ]
