# Generated by Django 5.2.3 on 2025-07-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spinwheelapp', '0005_shopprofile_whatsapp_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopprofile',
            name='whatsapp_number',
        ),
    ]
