# Generated by Django 5.2.3 on 2025-07-01 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinwheelapp', '0006_spinentry_country_code_alter_spinentry_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsettings',
            name='spins_per_day',
        ),
        migrations.RemoveField(
            model_name='spinentry',
            name='country_code',
        ),
        migrations.AlterField(
            model_name='spinentry',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid  phone number', regex='^[6-9]\\d{9}$')]),
        ),
    ]
