# Generated by Django 5.2.3 on 2025-07-04 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinwheelapp', '0006_remove_shopprofile_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopprofile',
            name='whatsapp_number',
            field=models.CharField(default='919988776655', help_text='WhatsApp number with country code (e.g. 919876543210)', max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Enter a valid phone number')]),
        ),
    ]
