# Generated by Django 5.2.3 on 2025-07-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinwheelapp', '0007_remove_shopsettings_spins_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='google_review_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='require_social_verification',
            field=models.BooleanField(default=False, help_text='Enable to require social media verification before spinning'),
        ),
    ]
