# Generated by Django 5.2.3 on 2025-07-01 12:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinwheelapp', '0008_shopsettings_google_review_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='require_screenshot',
            field=models.BooleanField(default=False, help_text='Enable to require screenshot proof for social verification'),
        ),
        migrations.CreateModel(
            name='SocialVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_screenshot', models.ImageField(help_text='Upload screenshot of Instagram follow', upload_to='verifications/instagram/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('google_review_screenshot', models.ImageField(help_text='Upload screenshot of Google review', upload_to='verifications/google/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_verification', to='spinwheelapp.spinentry')),
            ],
        ),
    ]
