# Generated by Django 5.2.3 on 2025-07-25 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinwheelapp', '0009_fix_bill_number_uniqueness'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='spinentry',
            name='unique_bill_per_shop',
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='allow_multiple_entries_per_phone',
            field=models.BooleanField(default=True, help_text='Allow the same phone number to spin multiple times per day (only applicable when bill number is not required)'),
        ),
        migrations.AddField(
            model_name='spinentry',
            name='is_redeemed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spinentry',
            name='short_id',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='whatsapp_number',
            field=models.CharField(default='8848647616', help_text='WhatsApp number with country code (e.g. 919876543210)', max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Enter a valid phone number')]),
        ),
        migrations.AlterField(
            model_name='spinentry',
            name='bill_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='spinentry',
            constraint=models.UniqueConstraint(condition=models.Q(('bill_number__isnull', False), models.Q(('bill_number', ''), _negated=True)), fields=('shop', 'bill_number'), name='unique_bill_per_shop'),
        ),
    ]
