# Generated by Django 5.2.3 on 2025-07-02 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinwheelapp', '0009_shopsettings_require_screenshot_socialverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinentry',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spinwheelapp.offer'),
        ),
    ]
