# Generated by Django 5.2.3 on 2025-07-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinwheelapp', '0009_fix_bill_number_uniqueness'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='spinentry',
            name='unique_bill_per_shop',
        ),
        migrations.AlterField(
            model_name='spinentry',
            name='bill_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='spinentry',
            constraint=models.UniqueConstraint(condition=models.Q(('bill_number__isnull', False), models.Q(('bill_number', ''), _negated=True)), fields=('shop', 'bill_number'), name='unique_bill_per_shop'),
        ),
    ]
