# Generated by Django 5.2.3 on 2025-07-24 07:24

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinwheelapp', '0010_remove_spinentry_unique_bill_per_shop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='shopprofile',
            name='whatsapp_number',
            field=models.CharField(default='8848647616', help_text='WhatsApp number with country code (e.g. 919876543210)', max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Enter a valid phone number')]),
        ),
        migrations.AlterField(
            model_name='spinentry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
