# Generated by Django 5.2.3 on 2025-07-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinwheelapp', '0011_alter_offer_name_alter_shopprofile_whatsapp_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinentry',
            name='short_id',
            field=models.CharField(default='temp', editable=False, max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spinentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
