# Generated by Django 5.2.3 on 2025-07-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinwheelapp', '0016_populate_short_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinentry',
            name='short_id',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True),
        ),
    ]
