# Generated by Django 5.2.3 on 2025-07-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinwheelapp', '0018_final_fix_short_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinentry',
            name='is_redeemed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spinentry',
            name='short_id',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True),
        ),
    ]
