# Generated by Django 5.2.3 on 2025-07-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinwheelapp', '0019_spinentry_is_redeemed_alter_spinentry_short_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='allow_multiple_entries_per_phone',
            field=models.BooleanField(default=True, help_text='Allow the same phone number to spin multiple times per day (only applicable when bill number is not required)'),
        ),
    ]
